### PR TITLE
Add caller name on onViewStateChange callback at NavigationControl

### PR DESCRIPTION
**Pull request by macabeus**
This PR adds a parameter at `onViewStateChange` callback at  `NavigationControl` component to return the name of the button that was clicked.

It is necessary when you want to do something when a specific button is clicked and the `viewState` wasn't update. For example, when the user is on the max zoom and clicked on `+` button, so maybe you want to show an alert.

I have a situation very similar that it on my project and so I'm opening this PR

### CODE REVIEW

**Comment by macabeus** [comment]
The build fails, but I think that the cause isn't by my PR...
```
browser-driver: Browser Test failed: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
```

Someone could help me, please?

**Comment by xintongxia** [comment]
> The build fails, but I think that the cause isn't by my PR...
> 
> ```
> browser-driver: Browser Test failed: Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
> ```
> 
> Someone could help me, please?

run `yarn upgrade` and then update your PR

**Comment by macabeus** [comment]
@xintongxia Now I'm receiving this error on test:

```
# Basic map
This page appears to be missing CSS declarations for Mapbox GL JS, which may cause the map to display incorrectly. Please ensure your page includes mapbox-gl.css, as described in https://www.mapbox.com/mapbox-gl-js/api/.
Failed to load resource: the server responded with a status of 401 (Unauthorized)
A valid API access token is required to use Mapbox data
not ok 266 Unauthorized: you may have provided an invalid Mapbox access token. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
  ---
    operator: fail
    stack: |-
      Error: Unauthorized: you may have provided an invalid Mapbox access token. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes
          at Test.assert [as _assert] (http://localhost:5000/test-browser.js:72595:54)
          at Test.bound [as _assert] (http://localhost:5000/test-browser.js:72447:32)
          at Test../node_modules/tape/lib/test.js.Test.fail (http://localhost:5000/test-browser.js:72688:10)
          at Test.bound [as fail] (http://localhost:5000/test-browser.js:72447:32)
          at http://localhost:5000/test-browser.js:118135:11
  ...
```

But apparently [this test already set a default token for me](https://github.com/macabeus/react-map-gl/blob/3e77f2a76e615ac9fbd50783dc020385f269d835/test/render/test-cases.js#L15)... do you know how to fix it, please?

**Comment by Pessimistress** [comment]
Closing for inactivity. This will be irrelevant in v7.

**Pull request closed without merging**
