### PR TITLE
fix `reuseMaps` actions wrong expectations

### PR DESCRIPTION
**Pull request by lh0x00**
In this PR I have solved issue #2071 
I've tried and created a temporary release in the meantime, you can check out the results [here](https://codesandbox.io/s/modern-breeze-v30usd?file=/src/Map.js), this forked from issue report.

Please review and review it, many thanks. ^^

cc @Pessimistress @theRuslan

### CODE REVIEW

**Comment by Pessimistress** [comment]
Thanks for the proposal. `cloneElement` could be quite expensive if there are a lot of child elements. Can you try wrapping all children in a single div and removing that div upon dismount?

**Comment by lh0x00** [comment]
I tried using react's ref but it didn't give the desired effect because the mechanism will go after we save the value, you can see more here https://github.com/visgl/react-map-gl/pull/2092/commits/2e4df069db0056c0db20f9481bcf51cad228cb13.

cc @Pessimistress

**Comment by lh0x00** [comment]
Please review and release it soon if possible, I'm really waiting for it. Thank you ^^.

**Review by Pessimistress — APPROVED** [review]

**Comment by Pessimistress** [comment]
Can you run `yarn lint fix`?

**Comment by lh0x00** [comment]
@Pessimistress it's ready to merge

**Pull request merged**
